from __future__ import annotations
import ctypes
import ctypes.wintypes
import enum
from typing import Literal
from typing_extensions import deprecated


class Winuser:
    """
    Using `win32con` module to instead this class of definitions is another choice.
    """

    class SystemMessage(enum.Enum):  # 3rd-party sheet of IDs: https://www.cnblogs.com/csnotes/p/17132012.html
        class WM_HOTKEY:
            def __index__(self) -> ctypes.c_uint32:
                """ (ctypes.wintypes.UINT)
                Posted when the user presses a hot key registered by the RegisterHotKey function.
                The message is placed at the top of the message queue associated with the thread that registered the
                hot key.

                ---

                WM_HOTKEY is unrelated to the WM_GETHOTKEY and WM_SETHOTKEY hot keys.
                The WM_HOTKEY message is sent for generic hot keys while the WM_SETHOTKEY and
                WM_GETHOTKEY messages relate to window activation hot keys.
                """

                return ctypes.c_uint32(0x0312)

            class wParam(enum.Enum):
                """ (ctypes.wintypes.UINT)
                The identifier of the hot key that generated the message. If the message was generated by a
                system-defined hot key, this parameter will be one of the following values.
                """

                IDHOT_SNAPDESKTOP = ctypes.wintypes.UINT(-2)  # The "snap desktop" hot key was pressed.
                IDHOT_SNAPWINDOW = ctypes.wintypes.UINT(-1)  # The "snap window" hot key was pressed.

            class lParam(enum.Flag):
                """ (ctypes.wintypes.UINT)
                The low-order word specifies the keys that were to be pressed in combination with the key specified by
                the high-order word to generate the WM_HOTKEY message. This word can be one or more of the
                following values. The high-order word specifies the virtual key code of the hot key.
                """

                MOD_ALT = 0x0001  # Either ALT key was held down.
                MOD_CONTROL = 0x0002  # Either CTRL key was held down.
                MOD_SHIFT = 0x0004  # Either SHIFT key was held down.
                MOD_WIN = 0x0008  # Either WINDOWS key was held down. These keys are labeled with the Windows logo.
                                  # Hotkeys that involve the Windows key are reserved for use by the operating system.

                MOD_NOREPEAT = 0x4000  # ONLY FOR the paramter `fsModifiers` of `User32.RegisterHotKey()`.
                                       #
                                       # Changes the hotkey behavior so that the keyboard auto-repeat does not
                                       # yield multiple hotkey notifications.
                                       #
                                       # Windows Vista: This flag is not supported.

    class VirtualKeyCode(enum.Enum):
        """ (ctypes.wintypes.UINT)
        ---

        Do not rely on the K_LWIN (0x5B) + VK_F17 (0x80) keys to permanently switch a setting. At shutdown,
        the system uses these keys to reset various settings, which could include those set by your app.

        ---

        0x07, 0x0A-0B, 0x5E, 0x88-8F, 0xB8-B9, 0xC1-C2, 0xE0 are Reserved.
        0x0E-0F, 0x97-9F, 0xE8 are Unassigned.
        0x3A-40 are Undefined.
        0x92-96, 0xE1, 0xE3-E4, 0xE6, 0xE9-F5 are OEM specific.
        """

        VK_LBUTTON = 0x01  # Left mouse button
        VK_RBUTTON = 0x02  # Right mouse button
        VK_CANCEL = 0x03  # Control-break processing
        VK_MBUTTON = 0x04  # Middle mouse button
        VK_XBUTTON1 = 0x05  # X1 mouse button
        VK_XBUTTON2 = 0x06  # X2 mouse button
        VK_BACK = 0x08  # Backspace key
        VK_TAB = 0x09  # Tab key
        VK_CLEAR = 0x0C  # Clear key
        VK_RETURN = 0x0D  # Enter key
        VK_SHIFT = 0x10  # Shift key
        VK_CONTROL = 0x11  # Ctrl key
        VK_MENU = 0x12  # Alt key
        VK_PAUSE = 0x13  # Pause key
        VK_CAPITAL = 0x14  # Caps lock key
        VK_KANA = 0x15  # IME Kana mode
        VK_HANGUL = 0x15  # IME Hangul mode
        VK_IME_ON = 0x16  # IME On
        VK_JUNJA = 0x17  # IME Junja mode
        VK_FINAL = 0x18  # IME final mode
        VK_HANJA = 0x19  # IME Hanja mode
        VK_KANJI = 0x19  # IME Kanji mode
        VK_IME_OFF = 0x1A  # IME Off
        VK_ESCAPE = 0x1B  # Esc key
        VK_CONVERT = 0x1C  # IME convert
        VK_NONCONVERT = 0x1D  # IME nonconvert
        VK_ACCEPT = 0x1E  # IME accept
        VK_MODECHANGE = 0x1F  # IME mode change request
        VK_SPACE = 0x20  # Spacebar key
        VK_PRIOR = 0x21  # Page up key
        VK_NEXT = 0x22  # Page down key
        VK_END = 0x23  # End key
        VK_HOME = 0x24  # Home key
        VK_LEFT = 0x25  # Left arrow key
        VK_UP = 0x26  # Up arrow key
        VK_RIGHT = 0x27  # Right arrow key
        VK_DOWN = 0x28  # Down arrow key
        VK_SELECT = 0x29  # Select key
        VK_PRINT = 0x2A  # Print key
        VK_EXECUTE = 0x2B  # Execute key
        VK_SNAPSHOT = 0x2C  # Print screen key
        VK_INSERT = 0x2D  # Insert key
        VK_DELETE = 0x2E  # Delete key
        VK_HELP = 0x2F  # Help key
        _0 = 0x30  # 0 key
        _1 = 0x31  # 1 key
        _2 = 0x32  # 2 key
        _3 = 0x33  # 3 key
        _4 = 0x34  # 4 key
        _5 = 0x35  # 5 key
        _6 = 0x36  # 6 key
        _7 = 0x37  # 7 key
        _8 = 0x38  # 8 key
        _9 = 0x39  # 9 key
        A = 0x41  # A key.
        B = 0x42  # B key.
        C = 0x43  # C key.
        D = 0x44  # D key.
        E = 0x45  # E key.
        F = 0x46  # F key.
        G = 0x47  # G key.
        H = 0x48  # H key.
        I = 0x49  # I key.
        J = 0x4A  # J key.
        K = 0x4B  # K key.
        L = 0x4C  # L key.
        M = 0x4D  # M key.
        N = 0x4E  # N key.
        O = 0x4F  # O key.
        P = 0x50  # P key.
        Q = 0x51  # Q key.
        R = 0x52  # R key.
        S = 0x53  # S key.
        T = 0x54  # T key.
        U = 0x55  # U key.
        V = 0x56  # V key.
        W = 0x57  # W key.
        X = 0x58  # X key.
        Y = 0x59  # Y key.
        Z = 0x5A  # Z key.
        VK_LWIN = 0x5B  # Left Windows logo key.
        VK_RWIN = 0x5C  # Right Windows logo key.
        VK_APPS = 0x5D  # Application key.
        VK_SLEEP = 0x5F  # Computer Sleep key.
        VK_NUMPAD0 = 0x60  # Numeric keypad 0 key.
        VK_NUMPAD1 = 0x61  # Numeric keypad 1 key.
        VK_NUMPAD2 = 0x62  # Numeric keypad 2 key.
        VK_NUMPAD3 = 0x63  # Numeric keypad 3 key.
        VK_NUMPAD4 = 0x64  # Numeric keypad 4 key.
        VK_NUMPAD5 = 0x65  # Numeric keypad 5 key.
        VK_NUMPAD6 = 0x66  # Numeric keypad 6 key.
        VK_NUMPAD7 = 0x67  # Numeric keypad 7 key.
        VK_NUMPAD8 = 0x68  # Numeric keypad 8 key.
        VK_NUMPAD9 = 0x69  # Numeric keypad 9 key.
        VK_MULTIPLY = 0x6A  # Multiply key.
        VK_ADD = 0x6B  # Add key.
        VK_SEPARATOR = 0x6C  # Separator key.
        VK_SUBTRACT = 0x6D  # Subtract key.
        VK_DECIMAL = 0x6E  # Decimal key.
        VK_DIVIDE = 0x6F  # Divide key.
        VK_F1 = 0x70  # F1 key.
        VK_F2 = 0x71  # F2 key.
        VK_F3 = 0x72  # F3 key.
        VK_F4 = 0x73  # F4 key.
        VK_F5 = 0x74  # F5 key.
        VK_F6 = 0x75  # F6 key.
        VK_F7 = 0x76  # F7 key.
        VK_F8 = 0x77  # F8 key.
        VK_F9 = 0x78  # F9 key.
        VK_F10 = 0x79  # F10 key.
        VK_F11 = 0x7A  # F11 key.
        VK_F12 = 0x7B  # F12 key.
        VK_F13 = 0x7C  # F13 key.
        VK_F14 = 0x7D  # F14 key.
        VK_F15 = 0x7E  # F15 key.
        VK_F16 = 0x7F  # F16 key.
        VK_F17 = 0x80  # F17 key.
        VK_F18 = 0x81  # F18 key.
        VK_F19 = 0x82  # F19 key.
        VK_F20 = 0x83  # F20 key.
        VK_F21 = 0x84  # F21 key.
        VK_F22 = 0x85  # F22 key.
        VK_F23 = 0x86  # F23 key.
        VK_F24 = 0x87  # F24 key.
        VK_NUMLOCK = 0x90  # Num lock key.
        VK_SCROLL = 0x91  # Scroll lock key.
        VK_LSHIFT = 0xA0  # Left Shift key.
        VK_RSHIFT = 0xA1  # Right Shift key.
        VK_LCONTROL = 0xA2  # Left Ctrl key.
        VK_RCONTROL = 0xA3  # Right Ctrl key.
        VK_LMENU = 0xA4  # Left Alt key.
        VK_RMENU = 0xA5  # Right Alt key.
        VK_BROWSER_BACK = 0xA6  # Browser Back key.
        VK_BROWSER_FORWARD = 0xA7  # Browser Forward key.
        VK_BROWSER_REFRESH = 0xA8  # Browser Refresh key.
        VK_BROWSER_STOP = 0xA9  # Browser Stop key.
        VK_BROWSER_SEARCH = 0xAA  # Browser Search key.
        VK_BROWSER_FAVORITES = 0xAB  # Browser Favorites key.
        VK_BROWSER_HOME = 0xAC  # Browser Start and Home key.
        VK_VOLUME_MUTE = 0xAD  # Volume Mute key.
        VK_VOLUME_DOWN = 0xAE  # Volume Down key.
        VK_VOLUME_UP = 0xAF  # Volume Up key.
        VK_MEDIA_NEXT_TRACK = 0xB0  # Next Track key.
        VK_MEDIA_PREV_TRACK = 0xB1  # Previous Track key.
        VK_MEDIA_STOP = 0xB2  # Stop Media key.
        VK_MEDIA_PLAY_PAUSE = 0xB3  # Play/Pause Media key.
        VK_LAUNCH_MAIL = 0xB4  # Start Mail key.
        VK_LAUNCH_MEDIA_SELECT = 0xB5  # Select Media key.
        VK_LAUNCH_APP1 = 0xB6  # Start Application 1 key.
        VK_LAUNCH_APP2 = 0xB7  # Start Application 2 key.
        VK_OEM_1 = 0xBA  # It can vary by keyboard. For the US ANSI keyboard , the Semiсolon and Colon key.
        VK_OEM_PLUS = 0xBB  # For any country/region, the Equals and Plus key.
        VK_OEM_COMMA = 0xBC  # For any country/region, the Comma and Less Than key.
        VK_OEM_MINUS = 0xBD  # For any country/region, the Dash and Underscore key.
        VK_OEM_PERIOD = 0xBE  # For any country/region, the Period and Greater Than key.
        VK_OEM_2 = 0xBF  # It can vary by keyboard. For the US ANSI keyboard, the Forward Slash and Question Mark key.
        VK_OEM_3 = 0xC0  # It can vary by keyboard. For the US ANSI keyboard, the Grave Accent and Tilde key.
        VK_GAMEPAD_A = 0xC3  # Gamepad A button.
        VK_GAMEPAD_B = 0xC4  # Gamepad B button.
        VK_GAMEPAD_X = 0xC5  # Gamepad X button.
        VK_GAMEPAD_Y = 0xC6  # Gamepad Y button.
        VK_GAMEPAD_RIGHT_SHOULDER = 0xC7  # Gamepad Right Shoulder button.
        VK_GAMEPAD_LEFT_SHOULDER = 0xC8  # Gamepad Left Shoulder button.
        VK_GAMEPAD_LEFT_TRIGGER = 0xC9  # Gamepad Left Trigger button.
        VK_GAMEPAD_RIGHT_TRIGGER = 0xCA  # Gamepad Right Trigger button.
        VK_GAMEPAD_DPAD_UP = 0xCB  # Gamepad D-pad Up button.
        VK_GAMEPAD_DPAD_DOWN = 0xCC  # Gamepad D-pad Down button.
        VK_GAMEPAD_DPAD_LEFT = 0xCD  # Gamepad D-pad Left button.
        VK_GAMEPAD_DPAD_RIGHT = 0xCE  # Gamepad D-pad Right button.
        VK_GAMEPAD_MENU = 0xCF  # Gamepad Menu/Start button.
        VK_GAMEPAD_VIEW = 0xD0  # Gamepad View/Back button.
        VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON = 0xD1  # Gamepad Left Thumbstick button.
        VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON = 0xD2  # Gamepad Right Thumbstick button.
        VK_GAMEPAD_LEFT_THUMBSTICK_UP = 0xD3  # Gamepad Left Thumbstick up.
        VK_GAMEPAD_LEFT_THUMBSTICK_DOWN = 0xD4  # Gamepad Left Thumbstick down.
        VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT = 0xD5  # Gamepad Left Thumbstick right.
        VK_GAMEPAD_LEFT_THUMBSTICK_LEFT = 0xD6  # Gamepad Left Thumbstick left.
        VK_GAMEPAD_RIGHT_THUMBSTICK_UP = 0xD7  # Gamepad Right Thumbstick up.
        VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN = 0xD8  # Gamepad Right Thumbstick down.
        VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT = 0xD9  # Gamepad Right Thumbstick right.
        VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT = 0xDA  # Gamepad Right Thumbstick left.
        VK_OEM_4 = 0xDB  # It can vary by keyboard. For the US ANSI keyboard, the Left Brace key.
        VK_OEM_5 = 0xDC  # It can vary by keyboard. For the US ANSI keyboard, the Backslash and Pipe key.
        VK_OEM_6 = 0xDD  # It can vary by keyboard. For the US ANSI keyboard, the Right Brace key.
        VK_OEM_7 = 0xDE  # can vary by keyboard. For the US ANSI keyboard, the Apostrophe and Double Quotation Mark key.
        VK_OEM_8 = 0xDF  # It can vary by keyboard. For the Canadian CSA keyboard, the Right Ctrl key.
        VK_OEM_102 = 0xE2  # It can vary by keyboard. For the European ISO keyboard, the Backslash and Pipe key.
        VK_PROCESSKEY = 0xE5  # IME PROCESS key.
        VK_PACKET = 0xE7  # Used to pass Unicode characters as if they were keystrokes. The VK_PACKET key is the
                          # low word of a 32-bit Virtual Key value used for non-keyboard input methods.
                          # For more information, see Remark in KEYBDINPUT, SendInput, WM_KEYDOWN, and WM_KEYUP.
        VK_ATTN = 0xF6  # Attn key.
        VK_CRSEL = 0xF7  # CrSel key.
        VK_EXSEL = 0xF8  # ExSel key.
        VK_EREOF = 0xF9  # Erase EOF key.
        VK_PLAY = 0xFA  # Play key.
        VK_ZOOM = 0xFB  # Zoom key.
        VK_NONAME = 0xFC  # Reserved.
        VK_PA1 = 0xFD  # PA1 key.
        VK_OEM_CLEAR = 0xFE  # Clear key.

    type VirtualKeyCodeType = Winuser.VirtualKeyCode | Literal[
        '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
        'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
        'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
        'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
        'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'
    ]


class Kernel32:
    @staticmethod
    def GetLastError() -> ctypes.wintypes.DWORD:
        """
        Retrieves the calling thread's last-error code value. The last-error code is maintained on a per-thread basis.
        Multiple threads do not overwrite each other's last-error code.

        ---

        Functions executed by the calling thread set this value by calling the SetLastError function.
        You should call the GetLastError function immediately when a function's return value indicates that such a
        call will return useful data. That is because some functions call SetLastError with a zero when they succeed,
        wiping out the error code set by the most recently failed function.

        To obtain an error string for system error codes, use the FormatMessage function. For a complete list of
        error codes provided by the operating system, see System Error Codes.

        The error codes returned by a function are not part of the Windows API specification and can vary by
        operating system or device driver. For this reason, we cannot provide the complete list of error codes that
        can be returned by each function. There are also many functions whose documentation does not include even a
        partial list of error codes that can be returned.

        Error codes are 32-bit values (bit 31 is the most significant bit). Bit 29 is reserved for
        application-defined error codes; no system error code has this bit set. If you are defining an error code for
        your application, set this bit to one. That indicates that the error code has been defined by an application,
        and ensures that your error code does not conflict with any error codes defined by the system.

        To convert a system error into an HRESULT value, use the HRESULT_FROM_WIN32 macro.

        :return:
        The return value is the calling thread's last-error code.

        The Return Value section of the documentation for each function that sets the last-error code notes the
        conditions under which the function sets the last-error code. Most functions that set the thread's last-error
        code set it when they fail. However, some functions also set the last-error code when they succeed.
        If the function is not documented to set the last-error code, the value returned by this function is simply
        the most recent last-error code to have been set; some functions set the last-error code to 0 on success and
        others do not.
        """

        return ctypes.windll.kernel32.GetLastError()


class User32:
    @deprecated('Not implemented as expectation.')
    @staticmethod
    def GetKeyboardState(
            lpKeyState: ctypes.wintypes.PBYTE | list
    ) -> ctypes.wintypes.BOOL:
        """
        Copies the status of the 256 virtual keys to the specified buffer.

        ---

        An application can call this function to retrieve the current status of all the virtual keys.
        The status changes as a thread removes keyboard messages from its message queue. The status does not change as
        keyboard messages are posted to the thread's message queue, nor does it change as keyboard messages are
        posted to or retrieved from message queues of other threads. (Exception: Threads that are connected through
        AttachThreadInput share the same keyboard state.)

        When the function returns, each member of the array pointed to by the lpKeyState parameter contains
        status data for a virtual key. If the high-order bit is 1, the key is down; otherwise, it is up.
        If the key is a toggle key, for example CAPS LOCK, then the low-order bit is 1 when the key is toggled and
        is 0 if the key is untoggled. The low-order bit is meaningless for non-toggle keys. A toggle key is said to be
        toggled when it is turned on. A toggle key's indicator light (if any) on the keyboard will be on when the key is
        toggled, and off when the key is untoggled.

        To retrieve status information for an individual key, use the GetKeyState function. To retrieve the
        current state for an individual key regardless of whether the corresponding keyboard message has been
        retrieved from the message queue, use the GetAsyncKeyState function.

        An application can use the virtual-key code constants VK_SHIFT, VK_CONTROL and VK_MENU as indices into the
        array pointed to by lpKeyState. This gives the status of the SHIFT, CTRL, or ALT keys without
        distinguishing between left and right. An application can also use the following virtual-key code constants as
        indices to distinguish between the left and right instances of those keys: VK_LSHIFT, VK_RSHIFT, VK_LCONTROL,
        VK_RCONTROL, VK_LMENU, VK_RMENU.

        These left- and right-distinguishing constants are available to an application only through the
        GetKeyboardState, SetKeyboardState, GetAsyncKeyState, GetKeyState, and MapVirtualKey functions.

        :return:
        If the function succeeds, the return value is nonzero.

        If the function fails, the return value is zero. To get extended error information, call GetLastError.

        :prarm lpKeyState: [out]
        The 256-byte array that receives the status data for each virtual key.
        """

        raise NotImplementedError()

        if isinstance(lpKeyState, list):
            _ArrayType = ctypes.wintypes.BYTE * 256
            arr = _ArrayType(*[0 for _ in range(256)])
            ctypes.wintypes.PBYTE(arr)

        ret = ctypes.windll.user32.GetKeyboardState(lpKeyState)

        if isinstance(lpKeyState, list) and ret != 0:
            lpKeyState.clear()
            for x in arr:
                lpKeyState.append(x)

        return ret

    @deprecated('Not implemented.')
    @staticmethod
    def GetKeyState(
            nVirtKey: ctypes.c_int32
    ) -> ctypes.wintypes.SHORT:
        raise NotImplementedError()

    @staticmethod
    def RegisterHotKey(
            hWnd: ctypes.wintypes.HWND | None,
            id_: ctypes.c_int32,
            fsModifiers: ctypes.wintypes.UINT | Winuser.SystemMessage.WM_HOTKEY.lParam,
            vk: ctypes.wintypes.UINT | Winuser.VirtualKeyCodeType
    ) -> ctypes.wintypes.BOOL:
        """
        Defines a system-wide hot key.

        ---

        When a key is pressed, the system looks for a match against all hot keys. Upon finding a match, the
        system posts the WM_HOTKEY message to the message queue of the window with which the hot key is associated.
        If the hot key is not associated with a window, then the WM_HOTKEY message is posted to the
        thread associated with the hot key.

        If a hot key already exists with the same hWnd and id parameters, it is maintained along with the new hot key.
        The application must explicitly call UnregisterHotKey to unregister the old hot key.

        The F12 key is reserved for use by the debugger at all times, so it should not be registered as a hot key.
        Even when you are not debugging an application, F12 is reserved in case a kernel-mode debugger or a
        just-in-time debugger is resident.

        An application must specify an id value in the range 0x0000 through 0xBFFF. A shared DLL must specify a
        value in the range 0xC000 through 0xFFFF (the range returned by the GlobalAddAtom function). To avoid
        conflicts with hot-key identifiers defined by other shared DLLs, a DLL should use the GlobalAddAtom function to
        obtain the hot-key identifier.

        Windows Server 2003: If a hot key already exists with the same hWnd and id parameters, it is replaced by the
        new hot key.

        :return:
        If the function succeeds, the return value is nonzero.

        If the function fails, the return value is zero. To get extended error information, call GetLastError.

        This function fails if you try to associate a hot key with a window created by another thread.

        Typically, RegisterHotKey also fails if the keystrokes specified for the hot key have already been
        registered for another hot key. However, some pre-existing, default hotkeys registered by the OS (such as
        PrintScreen, which launches the Snipping tool) may be overridden by another hot key registration when one of
        the app's windows is in the foreground.

        :param hWnd: [in, optional]
        A handle to the window that will receive WM_HOTKEY messages generated by the hot key. If this parameter is NULL,
        WM_HOTKEY messages are posted to the message queue of the calling thread and must be processed in
        the message loop.

        :param id_: [in]
        The identifier of the hot key. If the hWnd parameter is NULL, then the hot key is associated with the
        current thread rather than with a particular window. If a hot key already exists with the same hWnd and
        id parameters, see Remarks for the action taken.

        :param fsModifiers: [in]
        The keys that must be pressed in combination with the key specified by the vk parameter in order to generate the
        WM_HOTKEY message.

        :param vk: [in]
        The virtual-key code of the hot key. See Virtual Key Codes.
        """

        if hWnd is None:
            hWnd = ctypes.wintypes.HWND(None)
        if isinstance(fsModifiers, Winuser.SystemMessage.WM_HOTKEY.lParam):
            fsModifiers = ctypes.wintypes.UINT(fsModifiers.value)
        if isinstance(vk, Winuser.VirtualKeyCode):
            vk = ctypes.wintypes.UINT(vk.value)
        elif isinstance(vk, str):
            if len(vk) != 1:
                raise SyntaxError('vk must be a single character.')

            vk = ord(vk)

            if not (
                ord('0') <= vk <= ord('9') or
                ord('A') <= vk <= ord('Z') or
                ord('a') <= vk <= ord('z')
            ):
                raise SyntaxError('vk must be an alphabetic or numeric character.')

            vk = ctypes.wintypes.UINT(vk)


        return ctypes.windll.user32.RegisterHotKey(hWnd, id_, fsModifiers, vk)

    @staticmethod
    def UnregisterHotKey(
            hWnd: ctypes.wintypes.HWND | None,
            id_: ctypes.c_int32
    ) -> ctypes.wintypes.BOOL:
        """
        Frees a hot key previously registered by the calling thread.

        :return:
        If the function succeeds, the return value is nonzero.

        If the function fails, the return value is zero. To get extended error information, call GetLastError.

        :param hWnd: [in, optional]
        A handle to the window associated with the hot key to be freed. This parameter should be NULL if the
        hot key is not associated with a window.

        :param id_: [in]
        The identifier of the hot key to be freed.
        """

        if hWnd is None:
            hWnd = ctypes.wintypes.HWND(None)

        return ctypes.windll.user32.UnregisterHotKey(hWnd, id_)
