; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_TITLE "Count Anywhere"
!define PRODUCT_NAME "CountAnywhere"
!define PRODUCT_VERSION "0.1.0"
!define PRODUCT_PUBLISHER "Orange 233 <github.com/Orange23333>"
!define PRODUCT_WEB_SITE "https://www.ourorangenet.com"
!define PRODUCT_UNINST_KEY "Software/Microsoft/Windows/CurrentVersion/Uninstall/${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
!define PRODUCT_STARTMENU_REGVAL "NSIS:StartMenuDir"

SetCompressor lzma

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}/Contrib/Graphics/Icons/orange-install-nsis.ico"
!define MUI_UNICON "${NSISDIR}/Contrib/Graphics/Icons/orange-uninstall-nsis.ico"

; Language Selection Dialog Settings
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!insertmacro MUI_PAGE_LICENSE "../LICENSE"
; Components page
!insertmacro MUI_PAGE_COMPONENTS
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Start menu page
var ICONS_GROUP
!define MUI_STARTMENUPAGE_NODISABLE
!define MUI_STARTMENUPAGE_DEFAULTFOLDER "${PRODUCT_TITLE}"
!define MUI_STARTMENUPAGE_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "${PRODUCT_STARTMENU_REGVAL}"
!insertmacro MUI_PAGE_STARTMENU Application $ICONS_GROUP
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "SimpChinese"

; Reserve files
!insertmacro MUI_RESERVEFILE_INSTALLOPTIONS

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "${PRODUCT_NAME}-${PRODUCT_VERSION}-Setup.exe"
InstallDir "$PROGRAMFILES/Bisitsoft/${PRODUCT_NAME}"
ShowInstDetails show
ShowUnInstDetails show

Function .onInit
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Section "Core" SEC_CORE
  SetOverwrite ifnewer
  SetOutPath "$INSTDIR"
  File "resources.py"
  File "markers.py"
  File "main.py"
  File "i18n.py"
  File "globals_.py"
  File "__init__.py"
  SetOutPath "$INSTDIR/assets"
  File "assets/logo.png"
  File "assets/logo.ico"
  SetOutPath "$INSTDIR/locales"
  File "locales/zh-CN.yml"
  File "locales/en-US.yml"

; Shortcuts
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section "Desktop Shortcut" SEC_DESKTOP_SC
  SetOverwrite ifnewer
  SetOutPath "$DESKTOP"
  CreateShortCut "$DESKTOP/Count Anywhere.lnk" "$INSTDIR/CountAnywhere.exe"
SectonEnd

Section -AdditionalIcons
  SetOutPath $INSTDIR
  !insertmacro MUI_STARTMENU_WRITE_BEGIN Application
  CreateDirectory "$SMPROGRAMS/$ICONS_GROUP"
  CreateShortCut "${SMPROGRAMS}/${ICONS_GROUP}/Count Anywhere.lnk" "$INSTDIR/CountAnywhere.exe"
  CreateShortCut "${SMPROGRAMS}/${ICONS_GROUP}/Uninstall.lnk" "$INSTDIR/uninst.exe"
  !insertmacro MUI_STARTMENU_WRITE_END
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR/uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR/uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

; Section descriptions
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC_CORE} "Install core functions of Count Anywhere."
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC_DESKTOP_SC} "Add a shortcut on your desktop."
!insertmacro MUI_FUNCTION_DESCRIPTION_END


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从你的计算机移除。"
FunctionEnd

Function un.onInit
!insertmacro MUI_UNGETLANGUAGE
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你确实要完全移除 $(^Name) ，其及所有的组件？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  !insertmacro MUI_STARTMENU_GETFOLDER "Application" $ICONS_GROUP
  Delete "$INSTDIR/uninst.exe"
  Delete "$INSTDIR/locales/en-US.yml"
  Delete "$INSTDIR/locales/zh-CN.yml"
  Delete "$INSTDIR/assets/logo.ico"
  Delete "$INSTDIR/assets/logo.png"
  Delete "$INSTDIR/__init__.py"
  Delete "$INSTDIR/globals_.py"
  Delete "$INSTDIR/i18n.py"
  Delete "$INSTDIR/main.py"
  Delete "$INSTDIR/markers.py"
  Delete "$INSTDIR/resources.py"

  Delete "$DESKTOP/Count Anywhere.lnk"
  
  Delete "$SMPROGRAMS/$ICONS_GROUP/Count Anywhere.lnk"
  Delete "$SMPROGRAMS/$ICONS_GROUP/Uninstall.lnk"

  RMDir "$SMPROGRAMS/$ICONS_GROUP"
  RMDir "$INSTDIR/locales"
  RMDir "$INSTDIR/assets"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  SetAutoClose true
SectionEnd